#pragma config(Sensor, S4, irSensor, sensorEV3_IR)
#pragma config(Sensor, S3, sonarSensor, sensorSONAR)
#pragma config(Sensor, S1, colorSensor, sensorEV3_Color)
#pragma config(Motor, motorB, rightMotor, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorC, leftMotor, tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


 // 45-50; -- до банки
 // 60, 10; -- цвета (белый и черный)
 
task main(){
    int distance1;
    int distance2;
    int speed = 30;         // скорость моторов
    int speedR = 60;         // скорость моторов
    int bankCount = 0;      // количество сбитых банок
	const int reflectThreshold = 35;
    const int totalBanks = 8; // всего банок
	
	while(bankCount < totalBanks)
		{
		// Вращение на месте для поиска банки
		setMotorSpeed(leftMotor, speed);
		setMotorSpeed(rightMotor, -speed);

		distance1 = SensorValue[sonarSensor];
		distance2 = getIRDistance(irSensor);

 
        if(distance1 < 50 && distance1 > 0 && distance2 < 55 )// >0 чтобы исключить ошибочные чтения
        {
			// Остановить вращение
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
				wait10Msec(20);

			// Езда вперед и толкание банки до линии
			resetMotorEncoder(leftMotor);
			
            while(SensorValue[colorSensor] > reflectThreshold)
            {
                // Движение вперед, пока отражение не достигло линии
                setMotorSpeed(leftMotor, speedR);
                setMotorSpeed(rightMotor, speedR);
				wait10Msec(2);
            }

			// Остановились на линии
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			wait10Msec(20);

			// Возврат на исходное расстояние
			while(getMotorEncoder(leftMotor) > 0)
			{
				setMotorSpeed(leftMotor, -speedR);
				setMotorSpeed(rightMotor, -speedR);
			wait10Msec(2);

			}

			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			wait10Msec(20);

			// Увеличиваем счетчик сбитых банок
			bankCount++;
		}

		sleep(50); // основной цикл
	}

	// Все банки сбиты — остановка программы
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}
