#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     colorSensor,    sensorLightActive)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


 // 45-50; -- до банки
 // 70, 40; -- цвета (белый и черный)
 
task main(){
    int distance1;
    int speed = 30;         // скорость моторов
    int speedR = 30;         // скорость моторов
    int bankCount = 0;      // количество сбитых банок
	const int reflectThreshold = 55;
    const int totalBanks = 8; // всего банок
	
	while(bankCount < totalBanks)
		{
		// Вращение на месте для поиска банки
		setMotorSpeed(leftMotor, speed);
		setMotorSpeed(rightMotor, -speed);

		distance1 = SensorValue[sonarSensor];

 
        if(distance1 < 35 && distance1 > 0)// >0 чтобы исключить ошибочные чтения
        {
			// Остановить вращение
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
				wait10Msec(20);

			// Езда вперед и толкание банки до линии
			resetMotorEncoder(leftMotor);
			
            while(SensorValue[colorSensor] > reflectThreshold)
            {
                // Движение вперед, пока отражение не достигло линии
                setMotorSpeed(leftMotor, speedR);
                setMotorSpeed(rightMotor, speedR);
				wait10Msec(2);
            }

			// Остановились на линии
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			wait10Msec(20);

			// Возврат на исходное расстояние
			while(getMotorEncoder(leftMotor) > 0)
			{
				setMotorSpeed(leftMotor, -speedR);
				setMotorSpeed(rightMotor, -speedR);
			wait10Msec(2);
			}

			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			wait10Msec(20);

			// Увеличиваем счетчик сбитых банок
			bankCount++;
		}

		sleep(50); // основной цикл
	}

	// Все банки сбиты — остановка программы
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
}
