#pragma config(Sensor, S2, sonarSensor, sensorSONAR)
#pragma config(Sensor, S3, colorSensor, sensorLightActive)
#pragma config(Motor,  motorB, rightMotor, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC, leftMotor,  tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

task main()
{
    int distance;
    int speedSearch = 45;
    int speedPush   = 40;

    const int reflectThreshold = 55;
    const int totalBanks = 8;

    int bankCount = 0;

    while(bankCount < totalBanks)
    {
        // Поиск банки — вращение
        setMotorSpeed(leftMotor,  speedSearch);
        setMotorSpeed(rightMotor, -speedSearch);

        distance = SensorValue[sonarSensor];

        if(distance > 0 && distance < 36)
        {
            // Останов
            setMotorSpeed(leftMotor, 0);
            setMotorSpeed(rightMotor, 0);
            wait10Msec(20);

            // Сброс энкодеров
            resetMotorEncoder(leftMotor);
            resetMotorEncoder(rightMotor);

            // Толкаем банку до линии
            while(SensorValue[colorSensor] > reflectThreshold)
            {
                setMotorSpeed(leftMotor,  speedPush);
                setMotorSpeed(rightMotor, speedPush);
                wait10Msec(2);
            }

            // Останов на линии
            setMotorSpeed(leftMotor, 0);
            setMotorSpeed(rightMotor, 0);
            wait10Msec(20);

            // === ВАЖНО ===
            // Запоминаем, сколько реально проехали
            int forwardTicks = abs(getMotorEncoder(leftMotor));

            // Возврат назад на то же расстояние
            resetMotorEncoder(leftMotor);
            resetMotorEncoder(rightMotor);

            while(abs(getMotorEncoder(leftMotor)) < forwardTicks)
            {
                setMotorSpeed(leftMotor,  -speedPush);
                setMotorSpeed(rightMotor, -speedPush);
                wait10Msec(2);
            }

            // Полная остановка
            setMotorSpeed(leftMotor, 0);
            setMotorSpeed(rightMotor, 0);
            wait10Msec(20);

            bankCount++;
        }

        sleep(50);
    }

    // Все банки сбиты
    setMotorSpeed(leftMotor, 0);
    setMotorSpeed(rightMotor, 0);
}
