#pragma config(Sensor, S2,     gyro,           sensorAnalog)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void waitAfterTask()
{
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(500);
}

void rightRotation(int angle)
{
	while(SensorValue[gyro] < angle)
	{
		motor[motorB] = -30;
		motor[motorC] = 30;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;
	waitAfterTask();
}


void leftRotation(int angle)
{
		motor[motorB] = 30;
		motor[motorC] = -30;
		wait10Msec(100);
	}

	while(SensorValue[gyro] > angle)
		{
		motor[motorB] = 30;
		motor[motorC] = -30;

	}

	motor[motorB] = 0;
	motor[motorC] = 0;
	waitAfterTask();

	// return SensorValue[gyro];
}

void movingForvard(bool correction = false)
{
	if (correction)
	{
		motor[motorC] = 49;
		motor[motorB] = 48;
		wait10Msec(325);

		waitAfterTask();
	}
	else
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
		wait10Msec(325);

		waitAfterTask();
	}
}

task main()
{
	SensorType[gyro] = sensorAnalogInactive;
	wait1Msec(500);
	SensorValue[gyro] = 0;


	leftRotation(8700);
	wait10Msec (50);
	waitAfterTask();

	movingForvard();
	wait10Msec(50);
	waitAfterTask();

	movingForvard(true);
	wait10Msec(50);
	waitAfterTask();

	movingForvard();
	wait10Msec(50);
	waitAfterTask();

	movingForvard();
	wait10Msec(50);
	waitAfterTask();

	rightRotation(18000-300);
	wait10Msec (50);
	waitAfterTask();

	movingForvard();
	wait10Msec(50);
	waitAfterTask();

	movingForvard(true);
	wait10Msec(50);
	waitAfterTask();

	leftRotation(9000 + 300);
	wait10Msec(50);
	waitAfterTask();

	movingForvard();
	wait10Msec(50);
	waitAfterTask();
}
