#pragma config(Sensor, S2,     gyro,           sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void waitAfterTask()
{
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(500);
}

void rotation(int angle, bool isLeft = false)
{
	int turnThrowZero = 1;
	int motorDirectionMultipler = 1;
	int targetAngle = (angle * 100) - 300;

	if (isLeft)
	{
		if (SensorValue[gyro] < targetAngle)
		{
			turnThrowZero *= -1;
			targetAngle = 36000 - targetAngle;
		}
		motorDirectionMultipler = -1;
		targetAngle += 600 * turnThrowZero;
	}

	while(	SensorValue[gyro] * motorDirectionMultipler < targetAngle *
			motorDirectionMultipler *
			turnThrowZero)
	{
		motor[motorB] = -30 * motorDirectionMultipler;
		motor[motorC] = 30 * motorDirectionMultipler;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;
	waitAfterTask();
}

void movingForvard(int times = 1)
{
	for (int i = 0; i < times; i++)
	{
		if (i % 2 == 0)
		{
			motor[motorC] = 50;
			motor[motorB] = 49;
			wait10Msec(325);
	
			waitAfterTask();
		}
		
		else
		{
			motor[motorB] = 50;
			motor[motorC] = 50;
			wait10Msec(325);
	
			waitAfterTask();
		}
	}
}

task main()
{
	SensorType[gyro] = sensorAnalogInactive;
	wait1Msec(500);
	SensorValue[gyro] = 0;

	rotation(90);
	waitAfterTask();

	movingForvard(4);
	waitAfterTask();

	rightRotation(180);
	waitAfterTask();

	movingForvard(2);
	waitAfterTask();

	leftRotation(90, true);
	waitAfterTask();

	movingForvard();
	waitAfterTask();
}
