#pragma config(Sensor, S2,     gyro,           sensorAnalog)
#pragma config(Sensor, S3,     lightSensor,    sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void waitAfterTask(int times = 1)
{
	for (int i = 0; i < times; i++)
	{
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(500);
	}
}

void movingForvardUntilLine(int value,
														int speed = 50 /* Задел на будущее*/)
{
	while (SensorValue(lightSensor) > value)
	{
		motor[motorC] = speed;
		motor[motorB] = speed;
		wait1Msec(50);

		motor[motorB] = speed - 1;
		motor[motorC] = speed;
		wait1Msec(50);
	}
	waitAfterTask(2);
} // 1

void movingForvard(	int speed = 50, // Задел на будущее
										int duration = 325)
{
	motor[motorB] = speed;
	motor[motorC] = speed;
	wait10Msec(duration);
	waitAfterTask();
}

void rightRotation(int angle)
{
	while(SensorValue[gyro] < angle)
	{
		motor[motorB] = -30;
		motor[motorC] = 30;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;
	waitAfterTask();
}

task main()
{
	SensorType[gyro] = sensorAnalogInactive;
	wait1Msec(500);
	SensorValue[gyro] = 0;

	for (int i = 0; i < 4; i++)
	{
		movingForvardUntilLine(65);
		waitAfterTask(2);

		movingForvard(50, 220);
		waitAfterTask();

		rightRotation(((i + 1) * 90 * 100) - 300);
	}
}
