#pragma config(Sensor, S3, leftLight,  sensorLightActive)
#pragma config(Sensor, S2, rightLight, sensorLightActive)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int BASE_SPEED = 20;        // Ѕазова¤ скорость
const float TURN_GAIN = 1;      // зезкость поворота
const int TARGET = 50;            // целевое значение датчика (макс + мин)/2
const int TOLERANCE = 0;         // погрешность
const int SEARCH_SPEED = 10;      // скорость поиска
const int SEARCH_TIME = 300;      // врем¤ поиска
int DIR = 1;                      // изначальное направление поиска

bool onLine() {
	int L = SensorValue[leftLight];
	int R = SensorValue[rightLight];
	return (L < TARGET + TOLERANCE || R < TARGET + TOLERANCE);
}

void stopMotors() {
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	wait1Msec(100);
}


void rotationUntilLine(int dir) {
	while (true) {
		setMotorSpeed(leftMotor, SEARCH_SPEED * dir);
		setMotorSpeed(rightMotor, -SEARCH_SPEED * dir);
		wait1Msec(SEARCH_TIME);

		if (onLine()) {
			stopMotors();
			return;
		}

		setMotorSpeed(leftMotor, -SEARCH_SPEED * dir);
		setMotorSpeed(rightMotor, SEARCH_SPEED * dir);
		wait1Msec(SEARCH_TIME / 2);

		if (onLine()) {
			stopMotors();
			return;
		}
	}
}

void followLine() {
	while (true) {
		int leftVal = SensorValue[leftLight];
		int rightVal = SensorValue[rightLight];

		int error = leftVal - rightVal;

		int leftPower = BASE_SPEED - TURN_GAIN * error;
		int rightPower = BASE_SPEED + TURN_GAIN * error;

		setMotorSpeed(leftMotor, leftPower);
		setMotorSpeed(rightMotor, rightPower);

		if (leftVal > TARGET + TOLERANCE && rightVal > TARGET + TOLERANCE) {
			stopMotors();
			break;
		}

		wait1Msec(10);
	}
}

task main() {
	
	if (!onLine()) {
		rotationUntilLine(DIR);
	}

	while (true) {
		followLine();

		rotationUntilLine(DIR);
	}
}
