#pragma config(Sensor, S1, touchSensor, sensorTouch)
#pragma config(Sensor, S2, gyroSensor,  sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3, lightSensor, sensorLightActive)
#pragma config(Motor,  motorC, leftMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB, rightMotor, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

float Kp = 0.5;
int targetAngle = 0;
int error;
int motorCorrection;

// ================= ВСПОМОГАТЕЛЬНО =================

void stopMotors() {
	motor[leftMotor]  = 0;
	motor[rightMotor] = 0;
}

void moveBackward(int speed, int timeMs) {
	motor[leftMotor]  = -speed;
	motor[rightMotor] = -speed;
	wait1Msec(timeMs);
	stopMotors();
}

// ================= ПОВОРОТЫ =================

void turn180(int timeMs) {
	motor[leftMotor]  = 35;
	motor[rightMotor] = -35;
	wait1Msec(timeMs);
	stopMotors();
}

void turnLeft90(int timeMs) {
	motor[leftMotor]  = -35;
	motor[rightMotor] = 35;
	wait1Msec(timeMs);
	stopMotors();
}

void turnRight90(int timeMs) {
	motor[leftMotor]  = 35;
	motor[rightMotor] = -35;
	wait1Msec(timeMs);
	stopMotors();
}

// ================= ДВИЖЕНИЕ С КАСАНИЕМ =================

void moveForward(int angle, int speed) {
	while (true) {
		targetAngle = angle;
		error = targetAngle - SensorValue[gyroSensor];
		motorCorrection = (int)(Kp * error);

		motor[leftMotor]  = speed + motorCorrection;
		motor[rightMotor] = speed - motorCorrection;

		// 👉 УПЁРСЯ
		if (SensorValue[touchSensor] == 1) {
			stopMotors();
			wait1Msec(100);
			moveBackward(40, 150); // отъезд назад
			break;
		}
	}
	targetAngle = 0;
}

void moveForwardTimed(int angle, int speed, int duration) {
	clearTimer(T1);
	while (time1[T1] < duration) {
		targetAngle = angle;
		error = targetAngle - SensorValue[gyroSensor];
		motorCorrection = (int)(Kp * error);

		motor[leftMotor]  = speed + motorCorrection;
		motor[rightMotor] = speed - motorCorrection;
	}
	stopMotors();
	targetAngle = 0;
}

// ================= ЛИНИЯ =================

void waitForLine() {
	float lineKp = 5.5;
	int baseSpeed = 100;

	clearTimer(T1);
	while (time1[T1] < 15000) {
		int lineError = 85 - SensorValue[lightSensor];
		int correction = (int)(lineKp * lineError);

		motor[leftMotor]  = baseSpeed + correction;
		motor[rightMotor] = baseSpeed - correction;
	}
	stopMotors();
}

// ================= MAIN =================

task main() {
	SensorValue[gyroSensor] = 0;
	wait1Msec(500);

	turn180(1862);
	moveForward(1800,100);

	turnLeft90(931);
	moveForward(900,100);

	turnLeft90(931);
	moveForward(0,100);

	turnLeft90(931);
	moveForward(-900,100);

	turnRight90(931);
	moveForward(0,100);

	turnRight90(931);
	moveForward(900,100);

	turnLeft90(931);
	moveForward(0,100);

	turnLeft90(931);
	moveForward(-900,100);

	turnLeft90(931);
	moveForward(-1800,100);

	turnRight90(931);
	moveForward(-900,100);

	turnLeft90(931);
	moveForward(-1800,100);

	turnLeft90(931);
	moveForward(-2700,100);

	turnRight90(931);
	moveForward(-1800,100);

	turnRight90(931);
	moveForward(-900,100);

	turnLeft90(931);
	moveForward(-1800,100);

	turnLeft90(931);
	moveForward(-2700,100);

	turnRight90(931);
	moveForward(-1800,100);

	turnRight90(931);
	moveForward(-900,100);

	turnLeft90(931);
	moveForward(-1800,100);

	turnRight90(931);

	moveForwardTimed(-900,50,900);
	waitForLine();

	SensorValue[gyroSensor] = 0;

	moveForward(-900,100);
	turnLeft90(931);
	moveForward(-1800,100);

	turnRight90(931);
	moveForward(-900,100);

	turnRight90(931);
	moveForward(0,100);

	turnRight90(931);
	moveForward(900,100);

	turnRight90(931);
	moveForwardTimed(1800,100,2300);

	turnRight90(931);
	moveForward(2700,100);

	turnRight90(931);
	moveForward(3600,100);

	turnLeft90(931);
	moveForward(2700,100);

	turnLeft90(931);
	moveForward(1800,100);

	turnLeft90(931);
	moveForwardTimed(900,100,750);

	turnLeft90(931);
	moveForward(0,100);
}
