#pragma config(Sensor, S1, touchSensor, sensorEV3_Touch)
#pragma config(Sensor, S2, gyroSensor,        sensorEV3_Gyro)
#pragma config(Sensor, S3, lightSensor,       sensorEV3_Color)
#pragma config(Sensor, S4, sonar,       sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

void waitStop()
{
    setMotorSpeed(motorB, 0);
    setMotorSpeed(motorC, 0);
    wait1Msec(300);
}

//-------------------------------
// Поворот на месте по энкодеру
// degrees < 0  — против часовой
// degrees > 0  — по часовой

void rotation(int degrees)
{
    float L = 135.0;  // база робота
    float D = 56.0;   // диаметр колеса

    // Количество градусов, которое должен пройти мотор
    float wheelDegrees = (L * abs(degrees)) / D;

    resetMotorEncoder(motorB);
    resetMotorEncoder(motorC);

    // Поворот против часовой
    if(degrees > 0)
    {
        setMotorSpeed(motorB,  20);
        setMotorSpeed(motorC, -20);
    }
	// Поворот по часовой
    else   
    {
        setMotorSpeed(motorB, -29);
        setMotorSpeed(motorC,  29);
    }

    while(abs(getMotorEncoder(motorB)) < wheelDegrees) {}

    setMotorSpeed(motorB, 0);
    setMotorSpeed(motorC, 0);

    wait1Msec(300);
}

//-------------------------------
// Прямолинейное движение вперёд по расстоянию
void forward(float distance, int power)
{
    int target = ((distance * 30) / 17.6) * 360;

    resetMotorEncoder(motorB);
    resetMotorEncoder(motorC);

    setMotorSpeed(motorB, power);
    setMotorSpeed(motorC, power);

    while(abs(getMotorEncoder(motorB)) < target) {}

    waitStop();
}

//-------------------------------
// Движение вперёд до срабатывания сенсора касания
void forwardByTouch(int power)
{
    resetMotorEncoder(motorB);
    resetMotorEncoder(motorC);

    setMotorSpeed(motorB, power);
    setMotorSpeed(motorC, power);

    // Едем пока НЕ нажата
    while(SensorValue[touchSensor] == 0) {}

    // Откат назад 52 градусов
    resetMotorEncoder(motorB);
    resetMotorEncoder(motorC);

    setMotorSpeed(motorB, -power);
    setMotorSpeed(motorC, -power);

    while(abs(getMotorEncoder(motorB)) < 120) {}

    waitStop();
}

task main()
{
    setMotorSpeed(motorA,  30);
	wait1Msec(400);
	
    int turns[21] = {90, 90, 90, 90, 90, -90, -90, 90, 90, 90, -90, 90, 90, -90, -90, 90, 90, -90, -90, 90, -90};

    int n = 0;

	rotation(90);
    // while(true)
    // {
        // forwardByTouch(50);

        // if(n == 5 || n == 6 || n == 10)
        // {
            // rotation(90);
        // }
        // else
        // {
            // rotation(-90);
        // }

        // n++;
    // }
}
