#pragma config(Sensor, S1, touchSensor, sensorTouch)
#pragma config(Sensor, S3, lightSensor, sensorLightActive)
#pragma config(Motor,  motorC, leftMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB, rightMotor, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

void stopMotors() {
	motor[leftMotor]  = 0;
	motor[rightMotor] = 0;
}

void moveBackward(int speed, int timeMs) {
	motor[leftMotor]  = -speed;
	motor[rightMotor] = -speed;
	wait1Msec(timeMs);
	stopMotors();
}

void turn180(int timeMs) {
	motor[leftMotor]  = 35;
	motor[rightMotor] = -35;
	wait1Msec(timeMs);
	stopMotors();
}

void turnLeft90(int timeMs) {
	motor[leftMotor]  = -35;
	motor[rightMotor] = 35;
	wait1Msec(timeMs);
	stopMotors();
}

void turnRight90(int timeMs) {
	motor[leftMotor]  = 35;
	motor[rightMotor] = -35;
	wait1Msec(timeMs);
	stopMotors();
}

void moveForward(int speed) {
	while (true) {
		motor[leftMotor]  = speed;
		motor[rightMotor] = speed;

		if (SensorValue[touchSensor] == 1) {
			stopMotors();
			wait1Msec(100);
			moveBackward(40, 150);
			break;
		}
	}
}

void moveForwardTimed(int speed, int duration) {
	clearTimer(T1);
	while (time1[T1] < duration) {
		motor[leftMotor]  = speed;
		motor[rightMotor] = speed;
	}
	stopMotors();
}

void waitForLine() {
	float Kp = 5.5;
	int baseSpeed = 100;

	clearTimer(T1);
	while (time1[T1] < 15000) {
		int error = 85 - SensorValue[lightSensor];
		int correction = (int)(Kp * error);

		motor[leftMotor]  = baseSpeed + correction;
		motor[rightMotor] = baseSpeed - correction;
	}
	stopMotors();
}

task main() {

	turn180(1862);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnRight90(931);

	moveForwardTimed(50, 900);
	waitForLine();

	moveForward(100);
	turnLeft90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForwardTimed(100, 2300);

	turnRight90(931);
	moveForward(100);

	turnRight90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForward(100);

	turnLeft90(931);
	moveForwardTimed(100, 750);

	turnLeft90(931);
	moveForward(100);
}
