#pragma config(Sensor, S2, sonarSensor, sensorSONAR)
#pragma config(Sensor, S1, colorSensorF, sensorLightActive)
#pragma config(Sensor, S4, colorSensorB, sensorLightActive)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
    int distance;
    int speed = 100;         
	const int reflectThresholdF = 56;
	const int reflectThresholdB = 38;
  
  while(true)
    {
	distance = SensorValue[sonarSensor];

 	while (distance > 40){
    setMotorSpeed(leftMotor, speed);
    setMotorSpeed(rightMotor, -speed);
	distance = SensorValue[sonarSensor];
	}
	
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	wait10Msec(20);

	setMotorSpeed(leftMotor, speed);
	setMotorSpeed(rightMotor, speed);
	wait10Msec(20);
	while((SensorValue[colorSensorF] > reflectThresholdF) || (SensorValue[colorSensorB] > reflectThresholdB)){}
	
	speed *= -1;

    setMotorSpeed(leftMotor, 0);
    setMotorSpeed(rightMotor, 0);
    wait10Msec(20);
	}
}