#pragma config(Sensor, S2, sonarSensor, sensorSONAR)
#pragma config(Sensor, S3, colorSensorF, sensorLightActive)
#pragma config(Sensor, S1, colorSensorB, sensorLightActive)
#pragma config(Motor,  motorB, rightMotor, tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC, leftMotor,  tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

/* ===== НАСТРОЙКИ ===== */
const int reflectThresholdF = 56;
const int reflectThresholdB = 38;
const int speed = 90;
const int turnSpeed = 70;
const int enemyDistance = 50;

/* ===== ФЛАГ ПРИОРИТЕТА ===== */
bool lineOverride = false;

/* ===== ЗАЩИТА ЛИНИИ ===== */
task LineGuard()
{
    while (true)
    {
        int frontLight = SensorValue[colorSensorF];
        int backLight  = SensorValue[colorSensorB];

        /* ЗАДНЯЯ ЛИНИЯ — МАКС. ПРИОРИТЕТ */
        if (backLight <= reflectThresholdB)
        {
            lineOverride = true;

            setMotorSpeed(leftMotor, speed);
            setMotorSpeed(rightMotor, speed);
            wait1Msec(80);

            continue;
        }

        /* ПЕРЕДНЯЯ ЛИНИЯ */
        if (frontLight <= reflectThresholdF)
        {
            lineOverride = true;

            setMotorSpeed(leftMotor, -speed);
            setMotorSpeed(rightMotor, -speed);
            wait1Msec(250);

            setMotorSpeed(leftMotor, turnSpeed);
            setMotorSpeed(rightMotor, -turnSpeed);
            wait1Msec(600);

            continue;
        }

        lineOverride = false;
        wait1Msec(10);
    }
}

/* ===== ОСНОВНАЯ ЛОГИКА ===== */
task main()
{
    long startTime = nSysTime;

    startTask(LineGuard);

    while (nSysTime - startTime < 60000)
    {
        if (lineOverride)
        {
            wait1Msec(10);
            continue;
        }

        int distance = SensorValue[sonarSensor];

        if (distance > 0 && distance < enemyDistance)
        {
            // Атака
            setMotorSpeed(leftMotor, speed);
            setMotorSpeed(rightMotor, speed);
        }
        else
        {
            // Поиск
            setMotorSpeed(leftMotor, turnSpeed);
            setMotorSpeed(rightMotor, -turnSpeed);
        }

        wait1Msec(20);
    }

    stopTask(LineGuard);
    setMotorSpeed(leftMotor, 0);
    setMotorSpeed(rightMotor, 0);
}
