#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void waitAfterTask(int times = 1)
{
	for (int i = 0; i < times; i++)
	{
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(500);
	}
}

void movingForvardUntilLine(int value,
							int speed = 50)
{
	while (SensorValue(lightSensor) > value)
	{
		motor[motorC] = speed;
		motor[motorB] = speed;
		wait1Msec(50);

		motor[motorB] = speed - 1;
		motor[motorC] = speed;
		wait1Msec(50);
	}
	waitAfterTask(2);
}

void movingForward(	int speed = 50,
					int duration = 325)
{
	motor[motorB] = speed;
	motor[motorC] = speed;
	wait10Msec(duration);
	waitAfterTask();
}

void rotation(int angle, bool isLeft = false)
{
	int leftMultipler = 1, angleMultipler = angle / 45;

	if (isLeft) leftMultipler *= -1;

	motor[motorB] = -20;
	motor[motorC] = -20;
	wait1Msec(220);

	for (int i = 0; i < angleMultipler; i++)
	{
		motor[motorB] = -30 * leftMultipler;
		motor[motorC] =  30 * leftMultipler;

		wait10Msec(54);
	}
}

task main()
{
	for (int i = 0; i < 4; i++)
	{
		if (i==i)movingForvardUntilLine(65);


		movingForward(50, 220);
		waitAfterTask();

		rotation(90 + (4 * i));
	}
}
