#pragma config(Sensor, S1,     lightRight,     sensorLightActive)
#pragma config(Sensor, S2,     gyro,           sensorAnalog)
#pragma config(Sensor, S3,     sonarSensor,          sensorSONAR)
#pragma config(Sensor, S4,     lightLeft,      sensorLightActive)
#pragma config(Motor,  motorB, leftMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC, rightMotor, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main(){
	int baseSpeed = 50;      
	int Kp = 2;         
	
	int rotationTimer1 = 2215;
	int rotationTimer2 = 110;
	
	int t1 = 27500;
	int t2 = 31000;
	
	motor[motorB] = -30;
	motor[motorC] =  30;
	wait1Msec(rotationTimer1);

	motor[motorB] = 50;
	motor[motorC] = 50;
	wait10Msec(530);

	while(SensorValue[lightRight] > 25 || SensorValue[lightLeft] > 25)
    {
		int leftVal = SensorValue[lightLeft]; 
		int rightVal = SensorValue[lightRight];

		int error = leftVal - rightVal;       

		motor[leftMotor]  = baseSpeed - Kp * error;
		motor[rightMotor] = baseSpeed + Kp * error;
    }

	while(SensorValue[sonarSensor] > 25) 
	{
		motor[motorB] = 50;    
		motor[motorC] = 50;   
	}

	motor[motorB] = 0;
	motor[motorC] = 0;
	wait10Msec(5);

	motor[motorB] = -30;
	motor[motorC] =  30;
	wait10Msec(rotationTimer2);

	motor[motorB] = 50;
	motor[motorC] = 50;
	wait10Msec(120);

	clearTimer(T1);
  
	while(time1[T1] < t1)
	{
		int leftVal = SensorValue[lightLeft];
		int rightVal = SensorValue[lightRight];

		int error = leftVal - rightVal;  

		motor[leftMotor]  = baseSpeed - Kp * error;
		motor[rightMotor] = baseSpeed + Kp * error;
	}
	
	motor[motorB] = 50;
	motor[motorC] =  50;
	wait10Msec(320);

	clearTimer(T1);
  
	while(time1[T1] < t2)
	{
		int leftVal = SensorValue[lightLeft];  
		int rightVal = SensorValue[lightRight];

		int error = leftVal - rightVal;

		motor[leftMotor]  = baseSpeed - Kp * error;
		motor[rightMotor] = baseSpeed + Kp * error;
	}
    
	motor[motorB] = -30;
	motor[motorC] = 30;
	wait10Msec(5);

	motor[motorB] = 50;
	motor[motorC] =  50;
	wait10Msec(1000);
}
