#pragma config(Sensor, S3, leftLight,  sensorLightActive)
#pragma config(Sensor, S2, rightLight, sensorLightActive)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

// ================== НАСТРОЙКИ ==================
#define BASE_SPEED 10     // максимально допустимая стабильная скорость
#define TURN_GAIN  5     // коэффициент коррекции
#define LINE_THR   47      // порог линии (подбирается экспериментально) 65 - белый; 30 - черный

// =================================================

task main()
{
    int leftValue, rightValue;
    int error;
    int correction;

    while (true)
    {
        leftValue  = SensorValue[leftLight];
        rightValue = SensorValue[rightLight];

        // --- УСЛОВИЕ ФИНИША ---
        if (leftValue < LINE_THR && rightValue < LINE_THR)
        {
            motor[leftMotor]  = 0;
            motor[rightMotor] = 0;
            break;
        }

        // --- ОШИБКА ПОЛОЖЕНИЯ ---
        // линия под левым датчиком -> поворот влево
        // линия под правым датчиком -> поворот вправо
        error = rightValue - leftValue;

        correction = (int)(error * TURN_GAIN);

        motor[leftMotor]  = BASE_SPEED + correction;
        motor[rightMotor] = BASE_SPEED - correction;

        wait1Msec(5); // минимальная задержка для стабильности
    }
}
