#pragma config(Sensor, S3, leftLight,  sensorLightActive)
#pragma config(Sensor, S2, rightLight, sensorLightActive)
#pragma config(Motor,  motorB, rightMotor, tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC, leftMotor,  tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#define BASE_SPEED 20
#define TURN_GAIN  1
#define LINE_THR   50

task main()
{
    int leftValue, rightValue;
    int error;
    int correction;

    while (true)
    {
        leftValue  = SensorValue[leftLight];
        rightValue = SensorValue[rightLight];

        // Финиш — оба датчика на линии
        if (leftValue < LINE_THR && rightValue < LINE_THR)
        {
            motor[leftMotor]  = 0;
            motor[rightMotor] = 0;
            break;
        }

        // ВАЖНО: инвертированная ошибка из-за reversed моторов
        error = leftValue - rightValue;

        correction = (int)(error * TURN_GAIN);

        motor[leftMotor]  = BASE_SPEED + correction;
        motor[rightMotor] = BASE_SPEED - correction;

        wait1Msec(5);
    }
}
