#pragma config(Sensor, S3, leftLight,  sensorLightActive)
#pragma config(Sensor, S2, rightLight, sensorLightActive)
#pragma config(Motor,  motorB, rightMotor, tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC, leftMotor,  tmotorEV3_Large, PIDControl, reversed, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int threshold = 45;
const int baseSpeed = 20;  // отрицательное значение — движение вперёд для EV3

task main()
{
  int lightLeft, lightRight;
  int motorPowerLeft, motorPowerRight;

  while (true)
  {
    // Чтение значений отражённого света (0–100)
    lightLeft  = SensorValue[leftLight];
    lightRight = SensorValue[rightLight];

    // Условие остановки: оба датчика на чёрной линии
    if (lightLeft < threshold && lightRight < threshold)
    {
      break;
    }

    // Простое ПИД-подобное управление разницей
    motorPowerLeft  = baseSpeed;
    motorPowerRight = baseSpeed;

    if (lightLeft < threshold && lightRight > threshold)
    {
      // Съехал влево → поворот вправо
      motorPowerLeft  = baseSpeed / 1.1;
      motorPowerRight = baseSpeed * 1.1;
    }
    else if (lightLeft > threshold && lightRight < threshold)
    {
      // Съехал вправо → поворот влево
      motorPowerLeft  = baseSpeed * 1.1;
      motorPowerRight = baseSpeed / 1.1;
    }

    motor[rightMotor]  = motorPowerLeft;
    motor[leftMotor] = motorPowerRight;

    wait1Msec(20);
  }

  // Остановка моторов
  motor[rightMotor]  = 0;
  motor[leftMotor] = 0;

  displayCenteredBigTextLine(3, "FINISHED!");
  wait1Msec(2000);
}