#pragma config(Motor,  motorB, rightMotor, tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC, leftMotor,  tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

/* === НАСТРОЙКИ === */
const int SPEED_FORWARD = 100;   // скорость движения
const int SPEED_TURN    = 50;   // скорость поворота

const int TIME_FORWARD1 = 1200; // мс — первый участок
const int TIME_TURN     = 500;  // мс — поворот
const int TIME_FORWARD2 = 1500; // мс — второй участок

/* === СЛУЖЕБНЫЕ ФУНКЦИИ === */
void stopMotors()
{
    motor[leftMotor]  = 0;
    motor[rightMotor] = 0;
    wait1Msec(100);
}

void driveForward(int speed, int timeMs)
{
    motor[leftMotor]  = speed;
    motor[rightMotor] = speed;
    wait1Msec(timeMs);
    stopMotors();
}

void turnRight(int speed, int timeMs)
{
    motor[leftMotor]  = speed;
    motor[rightMotor] = -speed;
    wait1Msec(timeMs);
    stopMotors();
}

void turnLeft(int speed, int timeMs)
{
    motor[leftMotor]  = -speed;
    motor[rightMotor] = speed;
    wait1Msec(timeMs);
    stopMotors();
}

/* === ОСНОВНАЯ ПРОГРАММА === */
task main()
{
    // Участок 1 — прямо
    driveForward(SPEED_FORWARD, TIME_FORWARD1);

    // Финиш
    stopMotors();
    displayCenteredBigTextLine(3, "FINISHED");
    wait1Msec(2000);
}
